CREATE TABLE COMMENT(
	SEQ INT PRIMARY KEY auto_increment,
    ID VARCHAR(50) NOT NULL,
    BOARD_SEQ INT NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    DEL INT NOT NULL,
	WDATE DATE NOT NULL,
    CONSTRAINT FOREIGN_WITH_BBS
    FOREIGN KEY(BOARD_SEQ)
    REFERENCES BBS(SEQ)
);
